### ISSUE TITLE
This list is no more "curated"

### ISSUE THREAD

**Issue by elin-y** [pmuens/awesome-serverless#33]
The list is too long and includes partially outdated blogs.

**Comment by pmuens** [comment]
Hey @elin-y thanks for bringing this up 👍

Yes, I agree. It got pretty long over the last couple of months. I already have a todo to clean this up (move old links into an `ARCHIVE.md` document or something along those lines) but haven't found any time to do this.

**Comment by pmuens** [comment]
Closing since lots of cleanup happened over the course of the year...
